// Mocks generated by Mockito 5.3.2 from annotations
// in res_pay/test/transfer/provider/repo/transfer/transfer_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:res_pay_merchant/core/errors/failures.dart' as _i6;
import 'package:res_pay_merchant/features/payment/modules/transfer/provider/api/transfer/transfer_remote_api.dart'
    as _i4;
import 'package:res_pay_merchant/features/payment/modules/transfer/provider/model/transfer_create_input.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransferRemoteApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransferRemoteApi extends _i1.Mock implements _i4.TransferRemoteApi {
  MockTransferRemoteApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          _dio,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i2.Response<Map<String, dynamic>>>>
      createTransfer(_i7.CreateTransferInput? input) => (super.noSuchMethod(
            Invocation.method(
              #createTransfer,
              [input],
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i6.Failure,
                        _i2.Response<Map<String, dynamic>>>>.value(
                _FakeEither_1<_i6.Failure, _i2.Response<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #createTransfer,
                [input],
              ),
            )),
          ) as _i5.Future<
              _i3.Either<_i6.Failure, _i2.Response<Map<String, dynamic>>>>);
}
