// Mocks generated by Mockito 5.3.2 from annotations
// in res_pay/test/more/terms/view/terms_and_conditions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:res_pay_merchant/features/authentication/provider/model/terms_privacy_about_model.dart'
    as _i3;
import 'package:res_pay_merchant/features/dashboard/modules/more/modules/terms_and_conditions/controller/terms_cubit.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTermsState_0 extends _i1.SmartFake implements _i2.TermsState {
  _FakeTermsState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TermsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTermsCubit extends _i1.Mock implements _i2.TermsCubit {
  MockTermsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.TermPrivacyAboutModel> get terms => (super.noSuchMethod(
        Invocation.getter(#terms),
        returnValue: <_i3.TermPrivacyAboutModel>[],
      ) as List<_i3.TermPrivacyAboutModel>);
  @override
  _i2.TermsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTermsState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.TermsState);
  @override
  _i4.Stream<_i2.TermsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i2.TermsState>.empty(),
      ) as _i4.Stream<_i2.TermsState>);
  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void changeTermExpanded(int? index) => super.noSuchMethod(
        Invocation.method(
          #changeTermExpanded,
          [index],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void emit(_i2.TermsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onChange(_i5.Change<_i2.TermsState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
