// Mocks generated by Mockito 5.3.2 from annotations
// in res_pay/test/beneficiary/provider/repo/beneficiary_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:res_pay_merchant/core/errors/failures.dart' as _i7;
import 'package:res_pay_merchant/core/public_module/provider/api/api_connection.dart'
    as _i5;
import 'package:res_pay_merchant/features/payment/modules/transfer/provider/api/beneficiary/beneficiary_remote_api.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BeneficiaryRemoteApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockBeneficiaryRemoteApi extends _i1.Mock
    implements _i4.BeneficiaryRemoteApi {
  MockBeneficiaryRemoteApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set apiConnection(_i5.APIConnection? _apiConnection) => super.noSuchMethod(
        Invocation.setter(
          #apiConnection,
          _apiConnection,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          _dio,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<_i3.Either<_i7.Failure, _i2.Response<Map<String, dynamic>>>>
      createTransferBeneficiary({required Map<String, dynamic>? inputs}) =>
          (super.noSuchMethod(
            Invocation.method(
              #createTransferBeneficiary,
              [],
              {#inputs: inputs},
            ),
            returnValue: _i6.Future<
                    _i3.Either<_i7.Failure,
                        _i2.Response<Map<String, dynamic>>>>.value(
                _FakeEither_1<_i7.Failure, _i2.Response<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #createTransferBeneficiary,
                [],
                {#inputs: inputs},
              ),
            )),
          ) as _i6.Future<
              _i3.Either<_i7.Failure, _i2.Response<Map<String, dynamic>>>>);
  @override
  _i6.Future<_i3.Either<_i7.Failure, _i2.Response<Map<String, dynamic>>>>
      getBeneficiaries({String? method}) => (super.noSuchMethod(
            Invocation.method(
              #getBeneficiaries,
              [],
              {#method: method},
            ),
            returnValue: _i6.Future<
                    _i3.Either<_i7.Failure,
                        _i2.Response<Map<String, dynamic>>>>.value(
                _FakeEither_1<_i7.Failure, _i2.Response<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getBeneficiaries,
                [],
                {#method: method},
              ),
            )),
          ) as _i6.Future<
              _i3.Either<_i7.Failure, _i2.Response<Map<String, dynamic>>>>);
  @override
  _i6.Future<_i3.Either<_i7.Failure, _i2.Response<Map<String, dynamic>>>>
      favouriteToggle({String? beneficiaryUUiD}) => (super.noSuchMethod(
            Invocation.method(
              #favouriteToggle,
              [],
              {#beneficiaryUUiD: beneficiaryUUiD},
            ),
            returnValue: _i6.Future<
                    _i3.Either<_i7.Failure,
                        _i2.Response<Map<String, dynamic>>>>.value(
                _FakeEither_1<_i7.Failure, _i2.Response<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #favouriteToggle,
                [],
                {#beneficiaryUUiD: beneficiaryUUiD},
              ),
            )),
          ) as _i6.Future<
              _i3.Either<_i7.Failure, _i2.Response<Map<String, dynamic>>>>);
  @override
  _i6.Future<_i3.Either<_i7.Failure, _i2.Response<Map<String, dynamic>>>>
      deleteBeneficiery({required String? uuid}) => (super.noSuchMethod(
            Invocation.method(
              #deleteBeneficiery,
              [],
              {#uuid: uuid},
            ),
            returnValue: _i6.Future<
                    _i3.Either<_i7.Failure,
                        _i2.Response<Map<String, dynamic>>>>.value(
                _FakeEither_1<_i7.Failure, _i2.Response<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #deleteBeneficiery,
                [],
                {#uuid: uuid},
              ),
            )),
          ) as _i6.Future<
              _i3.Either<_i7.Failure, _i2.Response<Map<String, dynamic>>>>);
}
