// Mocks generated by Mockito 5.3.2 from annotations
// in res_pay/test/more/change_language/controller/change_language_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:res_pay_merchant/core/errors/failures.dart' as _i7;
import 'package:res_pay_merchant/core/services/local_storage_service.dart' as _i4;
import 'package:res_pay_merchant/features/authentication/modules/login/provider/model/logged_in_user_model.dart'
    as _i8;
import 'package:res_pay_merchant/features/dashboard/modules/more/modules/language/provider/model/language_model.dart'
    as _i2;
import 'package:res_pay_merchant/features/dashboard/modules/more/modules/language/provider/repository/language_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLanguageModel_0 extends _i1.SmartFake implements _i2.LanguageModel {
  _FakeLanguageModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalStorageService_2 extends _i1.SmartFake
    implements _i4.LocalStorageService {
  _FakeLocalStorageService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LanguageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLanguageRepository extends _i1.Mock
    implements _i5.LanguageRepository {
  MockLanguageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LanguageModel get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: _FakeLanguageModel_0(
          this,
          Invocation.getter(#data),
        ),
      ) as _i2.LanguageModel);
  @override
  set data(_i2.LanguageModel? _data) => super.noSuchMethod(
        Invocation.setter(
          #data,
          _data,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i2.LanguageModel>>>
      getLanguagesRepository() => (super.noSuchMethod(
            Invocation.method(
              #getLanguagesRepository,
              [],
            ),
            returnValue: _i6.Future<
                    _i3.Either<_i7.Failure, List<_i2.LanguageModel>>>.value(
                _FakeEither_1<_i7.Failure, List<_i2.LanguageModel>>(
              this,
              Invocation.method(
                #getLanguagesRepository,
                [],
              ),
            )),
          ) as _i6.Future<_i3.Either<_i7.Failure, List<_i2.LanguageModel>>>);
  @override
  _i6.Future<_i3.Either<_i7.Failure, Map<String, dynamic>>>
      setLanguageRepository({required String? apiLang}) => (super.noSuchMethod(
            Invocation.method(
              #setLanguageRepository,
              [],
              {#apiLang: apiLang},
            ),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, Map<String, dynamic>>>.value(
                    _FakeEither_1<_i7.Failure, Map<String, dynamic>>(
              this,
              Invocation.method(
                #setLanguageRepository,
                [],
                {#apiLang: apiLang},
              ),
            )),
          ) as _i6.Future<_i3.Either<_i7.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i4.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String?> get getUserToken => (super.noSuchMethod(
        Invocation.getter(#getUserToken),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
  @override
  _i6.Future<String?> get getUserCountry => (super.noSuchMethod(
        Invocation.getter(#getUserCountry),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
  @override
  _i6.Future<String?> get getUserCurrency => (super.noSuchMethod(
        Invocation.getter(#getUserCurrency),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
  @override
  _i6.Future<String?> get getUserUUID => (super.noSuchMethod(
        Invocation.getter(#getUserUUID),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
  @override
  _i6.Future<String?> get getUserPhone => (super.noSuchMethod(
        Invocation.getter(#getUserPhone),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
  @override
  _i6.Future<String?> get getUserPinCode => (super.noSuchMethod(
        Invocation.getter(#getUserPinCode),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
  @override
  _i6.Future<String?> get getUserId => (super.noSuchMethod(
        Invocation.getter(#getUserId),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
  @override
  bool get getUserTouchId => (super.noSuchMethod(
        Invocation.getter(#getUserTouchId),
        returnValue: false,
      ) as bool);
  @override
  bool get getUserFaceId => (super.noSuchMethod(
        Invocation.getter(#getUserFaceId),
        returnValue: false,
      ) as bool);
  @override
  _i6.Future<_i4.LocalStorageService> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<_i4.LocalStorageService>.value(
            _FakeLocalStorageService_2(
          this,
          Invocation.method(
            #init,
            [],
          ),
        )),
      ) as _i6.Future<_i4.LocalStorageService>);
  @override
  String readString(
    String? key, {
    String? defaultValue = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readString,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: '',
      ) as String);
  @override
  bool readBool(
    String? key, {
    bool? defaultValue = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBool,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: false,
      ) as bool);
  @override
  _i6.Future<void> writeKey(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeKey,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> writeSecureKey(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeSecureKey,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> removeSession() => (super.noSuchMethod(
        Invocation.method(
          #removeSession,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<String?> readSecureKey(
    String? key, {
    String? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readSecureKey,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);
  @override
  _i6.Future<void> removeKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #removeKey,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> removeAllSecureKeys() => (super.noSuchMethod(
        Invocation.method(
          #removeAllSecureKeys,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> removeAllKeysInSharedPreferences() => (super.noSuchMethod(
        Invocation.method(
          #removeAllKeysInSharedPreferences,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<bool> containKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containKey,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<bool> containSecureKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containSecureKey,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<void> setUserToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setUserToken,
          [token],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> setUserUUID(String? uuid) => (super.noSuchMethod(
        Invocation.method(
          #setUserUUID,
          [uuid],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> setUserPhone(String? phone) => (super.noSuchMethod(
        Invocation.method(
          #setUserPhone,
          [phone],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> setUserPinCode(String? pinCode) => (super.noSuchMethod(
        Invocation.method(
          #setUserPinCode,
          [pinCode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> setTouchIdValue({required bool? touchId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTouchIdValue,
          [],
          {#touchId: touchId},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> setUsername(String? name) => (super.noSuchMethod(
        Invocation.method(
          #setUsername,
          [name],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> setFaceIdValue({required bool? faceId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFaceIdValue,
          [],
          {#faceId: faceId},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> setUserCountry({required String? country}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserCountry,
          [],
          {#country: country},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> setUserCurrency({required String? currency}) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUserCurrency,
          [],
          {#currency: currency},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> setUserId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> cacheCurrentUser(_i8.LoggedInUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheCurrentUser,
          [user],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
