// Mocks generated by Mockito 5.3.2 from annotations
// in res_pay/test/authentcation/login/provider/repository/login_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:res_pay_merchant/core/errors/failures.dart' as _i5;
import 'package:res_pay_merchant/features/authentication/modules/login/provider/API/login_api.dart'
    as _i3;
import 'package:res_pay_merchant/features/authentication/modules/login/provider/model/login_input.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginApi extends _i1.Mock implements _i3.LoginApi {
  MockLoginApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Response<Map<String, dynamic>>>>
      loginAPI(_i7.LoginInput? input) => (super.noSuchMethod(
            Invocation.method(
              #loginAPI,
              [input],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i6.Response<Map<String, dynamic>>>>.value(
                _FakeEither_0<_i5.Failure, _i6.Response<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #loginAPI,
                [input],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i6.Response<Map<String, dynamic>>>>);
  @override
  _i4.Future<Map<String, dynamic>> loginWitRes({
    String? identityId,
    required String? password,
    String? phoneNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWitRes,
          [],
          {
            #identityId: identityId,
            #password: password,
            #phoneNumber: phoneNumber,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
