// Mocks generated by Mockito 5.3.2 from annotations
// in res_pay/test/favourite/provider/repo/favourite_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:res_pay_merchant/core/errors/failures.dart' as _i7;
import 'package:res_pay_merchant/core/public_module/provider/api/api_connection.dart'
    as _i2;
import 'package:res_pay_merchant/features/e_commerce/modules/favourite/provider/api/favourite_api.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAPIConnection_0 extends _i1.SmartFake implements _i2.APIConnection {
  _FakeAPIConnection_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FavouriteApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavouriteApi extends _i1.Mock implements _i5.FavouriteApi {
  MockFavouriteApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.APIConnection get apiConnection => (super.noSuchMethod(
        Invocation.getter(#apiConnection),
        returnValue: _FakeAPIConnection_0(
          this,
          Invocation.getter(#apiConnection),
        ),
      ) as _i2.APIConnection);
  @override
  set apiConnection(_i2.APIConnection? _apiConnection) => super.noSuchMethod(
        Invocation.setter(
          #apiConnection,
          _apiConnection,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_1(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i3.Dio);
  @override
  set dio(_i3.Dio? _dio) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          _dio,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<_i4.Either<_i7.Failure, _i3.Response<Map<String, dynamic>>>>
      addProductToFavourite(String? productUUID) => (super.noSuchMethod(
            Invocation.method(
              #addProductToFavourite,
              [productUUID],
            ),
            returnValue: _i6.Future<
                    _i4.Either<_i7.Failure,
                        _i3.Response<Map<String, dynamic>>>>.value(
                _FakeEither_2<_i7.Failure, _i3.Response<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #addProductToFavourite,
                [productUUID],
              ),
            )),
          ) as _i6.Future<
              _i4.Either<_i7.Failure, _i3.Response<Map<String, dynamic>>>>);
  @override
  _i6.Future<_i4.Either<_i7.Failure, _i3.Response<Map<String, dynamic>>>>
      deleteProductFromFavourite({
    required String? favouriteUUID,
    required String? productUUID,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #deleteProductFromFavourite,
              [],
              {
                #favouriteUUID: favouriteUUID,
                #productUUID: productUUID,
              },
            ),
            returnValue: _i6.Future<
                    _i4.Either<_i7.Failure,
                        _i3.Response<Map<String, dynamic>>>>.value(
                _FakeEither_2<_i7.Failure, _i3.Response<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #deleteProductFromFavourite,
                [],
                {
                  #favouriteUUID: favouriteUUID,
                  #productUUID: productUUID,
                },
              ),
            )),
          ) as _i6.Future<
              _i4.Either<_i7.Failure, _i3.Response<Map<String, dynamic>>>>);
  @override
  _i6.Future<_i4.Either<_i7.Failure, _i3.Response<Map<String, dynamic>>>>
      getFavouriteProducts() => (super.noSuchMethod(
            Invocation.method(
              #getFavouriteProducts,
              [],
            ),
            returnValue: _i6.Future<
                    _i4.Either<_i7.Failure,
                        _i3.Response<Map<String, dynamic>>>>.value(
                _FakeEither_2<_i7.Failure, _i3.Response<Map<String, dynamic>>>(
              this,
              Invocation.method(
                #getFavouriteProducts,
                [],
              ),
            )),
          ) as _i6.Future<
              _i4.Either<_i7.Failure, _i3.Response<Map<String, dynamic>>>>);
}
